package com.sltj.medical.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STEP_TABLE.
 */
public class stepTable {

    private Long id;
    private String date;
    private String step;
    private String kilometer;
    private String cal;

    public stepTable() {
    }

    public stepTable(Long id) {
        this.id = id;
    }

    public stepTable(Long id, String date, String step, String kilometer, String cal) {
        this.id = id;
        this.date = date;
        this.step = step;
        this.kilometer = kilometer;
        this.cal = cal;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getStep() {
        return step;
    }

    public void setStep(String step) {
        this.step = step;
    }

    public String getKilometer() {
        return kilometer;
    }

    public void setKilometer(String kilometer) {
        this.kilometer = kilometer;
    }

    public String getCal() {
        return cal;
    }

    public void setCal(String cal) {
        this.cal = cal;
    }

}
